app:
  version: 1.0.0.SNAPSHOT
  name: Avp Hotel Bookings

server:
  port: 8090
  contextPath: /

---
spring:
  profiles: dev, default
logging:
  level:
    com:
      avp:
        booking: DEBUG
datasource:
  booking:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      format-sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
logging:
  level:
    com:
      avp:
        booking: INFO
datasource:
  booking:
    url: jdbc:mysql://localhost:3306/booking
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      dialect: org.hibernate.dialect.MySQLDialect